/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the LICENSE file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#include "H5private.h"

H5_WARN_LARGE_STACK_OBJECTS_OFF

const char H5build_settings[]=
    "       SUMMARY OF THE HDF5 CONFIGURATION\n"
    "       =================================\n"
    "\n"
    "General Information:\n"
    "-------------------\n"
    "                   HDF5 Version: 2.2.0\n"
    "                  Configured on: 2026-07-13\n"
    "                  Configured by: Unix Makefiles\n"
    "                    Host system: Darwin-24.6.0\n"
    "              Uname information: Darwin\n"
    "                       Byte sex: \n"
    "             Installation point: /Users/xuning/Work/go-dem/libs/darwin_arm\n"
    "\n"
    "Compiling Options:\n"
    "------------------\n"
    "                     Build Mode: Release\n"
    "              Debugging Symbols: OFF\n"
    "                        Asserts: OFF\n"
    "                      Profiling: OFF\n"
    "             Optimization Level: OFF\n"
    "\n"
    "Linking Options:\n"
    "----------------\n"
    "                      Libraries: \n"
    "  Statically Linked Executables: OFF\n"
    "                        LDFLAGS: \n"
    "                     H5_LDFLAGS: \n"
    "                     AM_LDFLAGS: \n"
    "                Extra libraries: m;dl;Threads::Threads\n"
    "                       Archiver: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar\n"
    "                       AR_FLAGS: \n"
    "                         Ranlib: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib\n"
    "\n"
    "Languages:\n"
    "----------\n"
    "                              C: YES\n"
    "                     C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 17.0.0.17000604\n"
    "                       CPPFLAGS: \n"
    "                    H5_CPPFLAGS: \n"
    "                    AM_CPPFLAGS: \n"
    "                        C Flags:  -std=c11  -O3 -DNDEBUG\n"
    "                     H5 C Flags: -Wall;-Warray-bounds;-Wcast-qual;-Wconversion;-Wdouble-promotion;-Wextra;-Wformat=2;-Wformat-nonliteral;-Wframe-larger-than=16384;-Wimplicit-fallthrough;-Wnull-dereference;-Wunused-const-variable;-Wwrite-strings;-Wpedantic;-Wvolatile-register-var;-Wno-c++-compat;-Wbad-function-cast;-Wimplicit-function-declaration;-Wincompatible-pointer-types;-Wmissing-declarations;-Wpacked;-Wshadow;-Wswitch;-Wno-error=incompatible-pointer-types-discards-qualifiers;-Wunused-function;-Wunused-variable;-Wunused-parameter;-Wcast-align;-Wformat;-Wno-missing-noreturn\n"
    "                     AM C Flags: \n"
    "               Shared C Library: NO\n"
    "               Static C Library: YES\n"
    "\n"
    "\n"
    "                        Fortran: OFF\n"
    "               Fortran Compiler:  \n"
    "                  Fortran Flags:  \n"
    "               H5 Fortran Flags: \n"
    "               AM Fortran Flags: \n"
    "         Shared Fortran Library: NO\n"
    "         Static Fortran Library: YES\n"
    "               Module Directory: /Users/xuning/Work/go-dem/build3/hdf5_build/mod\n"
    "\n"
    "                            C++: OFF\n"
    "                   C++ Compiler:  \n"
    "                      C++ Flags:  \n"
    "                   H5 C++ Flags: \n"
    "                   AM C++ Flags: \n"
    "             Shared C++ Library: NO\n"
    "             Static C++ Library: YES\n"
    "\n"
    "                           Java: OFF\n"
    "                  Java Compiler:  \n"
    "\n"
    "\n"
    "Features:\n"
    "---------\n"
    "                     Parallel HDF5: OFF\n"
    "  Parallel Filtered Dataset Writes: \n"
    "                Large Parallel I/O: \n"
    "                High-level library: ON\n"
    "Dimension scales w/ new references: \n"
    "                  Build HDF5 Tests: OFF\n"
    "                  Build HDF5 Tools: OFF\n"
    "                      Threadsafety: OFF\n"
    "                       Concurrency: OFF\n"
    "               Default API mapping: v200\n"
    "    With deprecated public symbols: ON\n"
    "            I/O filters (external): \n"
    "                  _Float16 support: ON\n"
    "                     Map (H5M) API: \n"
    "                        Direct VFD: \n"
    "                        Mirror VFD: \n"
    "                     Subfiling VFD: \n"
    "                (Read-Only) S3 VFD: \n"
    "              (Read-Only) HDFS VFD: \n"
    "    Packages w/ extra debug output: \n"
    "                       API tracing: OFF\n"
    "              Using memory checker: OFF\n"
    "                  Use file locking: best-effort\n"
    "         Strict file format checks: OFF\n"
    "      Optimization instrumentation: \n"
;

H5_WARN_LARGE_STACK_OBJECTS_ON
